# -*- coding: utf-8 -*-

# Form3 implementation generated from reading ui file 'Enter_New_Item.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.resize(642, 748)
        self.label_2 = QtWidgets.QLabel(Form3)
        self.label_2.setGeometry(QtCore.QRect(30, 480, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form3)
        self.label_3.setGeometry(QtCore.QRect(30, 570, 51, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.okButton = QtWidgets.QPushButton(Form3)
        self.okButton.setGeometry(QtCore.QRect(20, 660, 111, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.name_textEdit_2 = QtWidgets.QTextEdit(Form3)
        self.name_textEdit_2.setGeometry(QtCore.QRect(80, 480, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.name_textEdit_2.setFont(font)
        self.name_textEdit_2.setObjectName("name_textEdit_2")
        self.price_textEdit_3 = QtWidgets.QTextEdit(Form3)
        self.price_textEdit_3.setGeometry(QtCore.QRect(80, 570, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.price_textEdit_3.setFont(font)
        self.price_textEdit_3.setObjectName("price_textEdit_3")
        self.tableView = QtWidgets.QTableView(Form3)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 621, 451))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(15)
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "登入新品項"))
        self.label_2.setText(_translate("Form3", "品名:"))
        self.label_3.setText(_translate("Form3", "價格:"))
        self.okButton.setText(_translate("Form3", "確定"))
